fix: job

diff --git a/helm/kai/templates/engine/admin-api/minio-config-job.yaml b/helm/kai/templates/engine/admin-api/minio-config-job.yaml
--- a/helm/kai/templates/engine/admin-api/minio-config-job.yaml
+++ b/helm/kai/templates/engine/admin-api/minio-config-job.yaml
@@ -17,16 +17,10 @@ spec:
         - name: minio-client-config
           image: minio/mc
           env:
-            # set tier provider
+            # Set tier provider
             {{- if or (and .Values.config.minio.tier.aws.auth.secretName .Values.config.minio.tier.aws.auth.secretKeyNames.accessKey .Values.config.minio.tier.aws.auth.secretKeyNames.secretKey) (and .Values.config.minio.tier.aws.auth.accessKeyID .Values.config.minio.tier.aws.auth.secretAccessKey) }}
-            - name: SELECTED_TIER
+            - name: TIER_SELECTED
               value: "aws"
-            {{- else if or (and .Values.config.minio.tier.gcp.auth.secretName .Values.config.minio.tier.gcp.auth.secretKeyNames.credentials) (.Values.config.minio.tier.gcp.auth.credentials) }}
-            - name: SELECTED_TIER
-              value: "gcp"
-            {{- else if or (and .Values.config.minio.tier.azure.auth.secretName .Values.config.minio.tier.azure.auth.secretKeyNames.account .Values.config.minio.tier.azure.auth.secretKeyNames.key) (and .Values.config.minio.tier.azure.auth.accountName .Values.config.minio.tier.azure.auth.accountKey) }}
-            - name: SELECTED_TIER
-              value: "azure"
             {{- end }}
 
             # MINIO config
@@ -34,14 +28,23 @@ spec:
               value: "http://{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
             - name: REMOTE_BUCKET_NAME
               value: {{ .Values.config.minio.tier.remoteBucketName }}
-            ## tier (set in values / default)
+            ## tier.name (set in values / default)
+            {{- if .Values.config.minio.tier.name }}
+            - name: TIER_NAME
+              value: {{ .Values.config.minio.tier.name }}
+            {{- else }}
+            - name: TIER_NAME
+              value: {{ include "minio-config.tier.name" . }}
+            {{- end }}
+            ## remotePrefix (set in values / default)
             {{- if .Values.config.minio.tier.aws.remotePrefix }}
             - name: REMOTE_PREFIX
-              value: "{{ .Values.config.minio.tier.remotePrefix }}"
+              value: {{ .Values.config.minio.tier.remotePrefix }}
             {{- else }}
             - name: REMOTE_PREFIX
-              value: "{{ include "minio-config.tier.s3.remotePrefix" . }}"
+              value: {{ include "minio-config.tier.s3.remotePrefix" . }}
             {{- end }}
+            ## values from minio subchart
             - name: MINIO_ROOT_USER
               valueFrom:
                 secretKeyRef:
@@ -76,68 +79,41 @@ spec:
             ## endpointURL (set in values / default)
             {{- if .Values.config.minio.tier.aws.endpointURL }}
             - name: AWS_ENDPOINT_URL_S3
-              value: "{{ .Values.config.minio.tier.aws.endpointURL }}"
+              value: {{ .Values.config.minio.tier.aws.endpointURL }}
             {{- else }}
             - name: AWS_ENDPOINT_URL_S3
-              value: "{{ include "minio-config.tier.s3.endpointURL" . }}"
+              value: {{ include "minio-config.tier.s3.endpointURL" . }}
             {{- end }}
             ## region (set in values / default)
             {{- if .Values.config.minio.tier.aws.region }}
             - name: AWS_REGION
-              value: "{{ .Values.config.minio.tier.aws.region }}"
+              value: {{ .Values.config.minio.tier.aws.region }}
             {{- else }}
             - name: AWS_REGION
-              value: "{{ include "minio-config.tier.s3.region" . }}"
+              value: {{ include "minio-config.tier.s3.region" . }}
             {{- end }}
 
-            # GCP config
-            ## in case of existing secret keys
-            {{- if .Values.config.minio.tier.gcp.auth.secretName }}
-            - name: CREDENTIALS
-              valueFrom:
-                secretKeyRef:
-                  name: {{ .Values.config.minio.tier.gcp.auth.secretName }}
-                  key: {{ .Values.config.minio.tier.gcp.auth.secretKeyNames.credentials }}
-            ## in case of set keys in values.yaml
-            {{- else }}
-            - name: CREDENTIALS
-              value: {{ .Values.config.minio.tier.gcp.auth.credentials }}
-            {{- end }}
-
-            # Azure config
-            ## in case of existing secret keys
-            {{- if .Values.config.minio.tier.azure.auth.secretName }}
-            - name: ACCOUNT_NAME
-              valueFrom:
-                secretKeyRef:
-                  name: {{ .Values.config.minio.tier.azure.auth.secretName }}
-                  key: {{ .Values.config.minio.tier.azure.auth.secretKeyNames.account }}
-            - name: ACCOUNT_KEY
-              valueFrom:
-                secretKeyRef:
-                  name: {{ .Values.config.minio.tier.azure.auth.secretName }}
-                  key: {{ .Values.config.minio.tier.azure.auth.secretKeyNames.key }}
-            ## in case of set keys in values.yaml
-            {{- else }}
-            - name: ACCOUNT_NAME
-              value: {{ .Values.config.minio.tier.azure.auth.accountName }}
-            - name: ACCOUNT_KEY
-              value: {{ .Values.config.minio.tier.azure.auth.accountKey }}
-            {{- end }}
           command: ["/bin/bash", "-c"]
           args:
             - |
-              curl --retry 20 --retry-delay 2 -f --retry-all-errors ${KAI_MINIO_ENDPOINT_URL}/minio/health/live
-              curl -I ${KAI_MINIO_ENDPOINT_URL}/minio/health/live
+              echo -e "Checking MinIO \`/health/live\` endpoint until get 200 code..."
+              until [ "$(curl -s -w '%{http_code}' -o /dev/null "${KAI_MINIO_ENDPOINT_URL}/minio/health/live")" -eq 200 ]; do sleep 2; done
+              echo -e "200 Ok \nMinIO is UP and Running, configuring MinIO client (mc) against MinIO server"
               mc alias set kai-minio $KAI_MINIO_ENDPOINT_URL $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
-              if [ "$SELECTED_TIER" == "aws" ]; then
-                mc ilm tier add s3 kai-minio KONSTELLATION --endpoint $AWS_ENDPOINT_URL_S3 --access-key $AWS_ACCESS_KEY --secret-key $AWS_SECRET_ACCESS_KEY --bucket $REMOTE_BUCKET_NAME --prefix $REMOTE_PREFIX --region $AWS_REGION --force
-              elif [ "$SELECTED_TIER" == "gcp" ]; then
-                echo "$CREDENTIALS" > ./credentials.json
-                mc ilm tier add gcs kai-minio KONSTELLATION --credentials-file ./credentials.json --bucket $REMOTE_BUCKET_NAME --prefix $REMOTE_PREFIX --force
-              elif [ "$SELECTED_TIER" == "azure" ]; then
-                mc ilm tier add azure kai-minio KONSTELLATION --account-name $ACCOUNT_NAME --account-key $ACCOUNT_KEY --bucket $REMOTE_BUCKET_NAME --prefix $REMOTE_PREFIX --force
+              if [ "$TIER_SELECTED" == "aws" ]; then
+                echo -e "Tier provider selected: [AWS S3] \nChecking required variables for this tier"
+                variables=("TIER_NAME" "AWS_ENDPOINT_URL_S3" "AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "REMOTE_BUCKET_NAME" "REMOTE_PREFIX" "AWS_REGION")
+                for var in "${variables[@]}"; do
+                  if [ -z "${!var}" ]; then
+                    echo "ERROR: The variable $var is undefined or empty."
+                    exit 1
+                  fi
+                done
+                echo "All required variables are defined, creating the MinIO tier"
+                mc ilm tier add s3 kai-minio $TIER_NAME --endpoint $AWS_ENDPOINT_URL_S3 --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --bucket $REMOTE_BUCKET_NAME --prefix $REMOTE_PREFIX --region $AWS_REGION --force
+                echo "Job completed successfully!"
               else
                 echo "Minio Tier was enabled, but no specific configuration has been found for any Tier. Please check '.Values.config.minio.tier' section"
                 exit 1
+              fi
 {{- end }}
